name: CI/CD

on:
  push:
    branches:
      - prod
  pull_request:
    branches:
      - prod

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        python -m unittest discover

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Install Vercel CLI
      run: |
        npm install -g vercel

    - name: Deploy to Vercel
      run: |
        vercel --token ${{ secrets.VERCEL_TOKEN }} --prod --confirm
